### ISSUE TITLE
Fails on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#1]
The report seems to have MySQL specific custom queries. This leads to fatal errors on PostgreSQL (and probably other DBs that Moodle supports), such as:

```
ERROR: syntax error at or near ")"
LINE 4: CONVERT(gg.finalgrade,DECIMAL(3,0)) AS grade,
^
SELECT c.id AS courseid,
c.fullname AS coursename,
gi.itemname AS assessmentname,
CONVERT(gg.finalgrade,DECIMAL(3,0)) AS grade,
```

Do you think it's possible to convert them to queries that are cross-db
compatible? Operations like rounding can be do at the PHP level maybe?

**Comment by jgramp** [comment]
I have now moved the code that changes the decimal places to 0 into the php, so the query should now work across databases. Thank you for picking up on this and all your additional feedback. Resolved in version 1.2
