### ISSUE TITLE
Activities duplicated on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#10]
### Steps to reproduce
1. In a course, prepare an Assignment, Quiz and Workshop
2. Let a student to submit into the Assignment and the Workshop, and attempt the Quiz
3. As a teacher, grade the Assignment and the Workshop. Evaluate and close the workshop.
### Expected behaviour
- The report should display 3 entries, each activity on its own row
### Actual behaviour
- There are six rows in the report, each activity is duplicated there.

![myreport-bug](https://cloud.githubusercontent.com/assets/85831/6489525/4ac28688-c29f-11e4-9057-838abfb86b4c.png)

**Comment by jgramp** [comment]
I can't replicate this issue in either database. Are you testing on version 1.5 or 1.6? These should both work similarly. 1.4 and earlier did have a problem with duplicate entries, but the SQL now includes 'SELECT DISTINCT ' to remedy this.

**Comment by mudrd8mz** [comment]
1.5 (Build: 2015022701), the most recent one that was available at the time I was testing it. I will give the automatic update notification a chance tomorrow to see if 1.6 fixes it.

**Comment by mudrd8mz** [comment]
Just updated to 1.6 and can still reproduce this. My environment: PHP 5.5.20, PostgreSQL 9.3.5

**Comment by marcusgreen** [comment]
I have installed $plugin->release = '1.6 (Build: 2015030401), on Windows 7 under XAMPP (with MySQL) and I am getting a similar errors.

I have two courses with quizzes and assignments. One quiz is showing up twice on one course, the other items are showing correctly. I have looked closely to see if I can see a difference that might be causing it but I have not found anything yet. 

Will probably be installing it under a test Linux system and will let you know if that shows the same problem.

**Comment by jgramp** [comment]
Hi Marcus and David,

Would you mind sending me the course export so I can try and replicate it here on my own installs of moodle with mysql and postgres? I'm not seeing any double ups and can't understand why.

Thank you.

**Comment by marcusgreen** [comment]
I have just noticed a key difference between the two courses, one has a non core question type (my own Gapfill question type) in it. I have backed up that course and attached to this message. Ahh, it doesn't seem to allow me to do that :(. I have sent you a message via Moodle.org

**Comment by marcusgreen** [comment]
I have just experimented further and I don't think there is anything to do with non core question types (which seemed unlikely)

**Comment by jgramp** [comment]
Fixed in v1.9 with duplicates appearing in the report in Moodle 2.7+ when a word limit is enabled in online text Assignments.
