### ISSUE TITLE
Why is $remotedb hard-coded to mysqli_native_moodle_database?

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#3]
If you achieve to make the code cross-db compatible (as reported in #1), it would make sense to make the remote DB engine configurable, too. You may want to use the same DB engine selector that the Moodle installer has.

**Comment by jgramp** [comment]
Made code cross-db compatible - the remote DB will use the same db type as the Moodle $DB object, since the external database is expected to be an exact duplicate of the Moodle DB. Changes implemented in version 1.2.
