### ISSUE TITLE
Notices and missing div element

### ISSUE THREAD

**Issue by johnnypraxis** [jgramp/moodle-report_myfeedback#32]
The properties "profile_field_year" and "profile_field_programmename" to isn't defined and throws notices. Closing div element missing in the overview.php file caausing layout error.

Screenshot of the issues:
http://screencast.com/t/PS5Qrq9lZmZE

Pull request to solve the issues:
https://github.com/jgramp/moodle-report_myfeedback/pull/31

Please update the plugin on moodle.org when issues are fixed :-)

Best regards
Johnny Drud

**Comment by johnnypraxis** [comment]
Btw. the feedback report on the screenshot is installed on a Moodle v. 2.9.4.

**Comment by jgramp** [comment]
Thank Johnny. The developer used your fix and it's in the latest version :)
