### ISSUE TITLE
Embedding javascript

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#4]
The code seems to inject the jQuery code in a very non-standard way by echoing it after `$OUTPUT->footer();` I am afraid this leads to the script code being generated only after the closing </html> tag, am I right? Please see https://docs.moodle.org/dev/jQuery for the recommended way to include jQuery in Moodle plugins.

**Comment by jgramp** [comment]
moved the embedded javascript to before the footer output in version 1.2
