### ISSUE TITLE
PHP8.0 Required Parameter

### ISSUE THREAD

**Issue by aspark21** [jgramp/moodle-report_myfeedback#44]
Deprecated: Required parameter $modt follows optional parameter $search in /var/www/html/report/myfeedback/lib.php on line 1454
  
    Deprecated: Required parameter $proga follows optional parameter $search in /var/www/html/report/myfeedback/lib.php on line 1454

**Comment by opitz** [comment]
I have fixed this in CTP-1582 as it caused Behat tests to fail.
