### ISSUE TITLE
Return value of report_myfeedback\local\report::get_group_assign_submission_date() must be of the type string, null returned

### ISSUE THREAD

**Issue by superfoght** [jgramp/moodle-report_myfeedback#46]
We have several sites where both students, teachers, and admins get the follwoing error:
Return value of report_myfeedback\local\report::get_group_assign_submission_date() must be of the type string, null returned

![image](https://user-images.githubusercontent.com/2778015/217481881-1357fbb1-c557-44aa-93f2-a8810d72c70d.png)

**Comment by aspark21** [comment]
Which version of Moodle?
Which version of the plugin?

**Comment by superfoght** [comment]
Thanks for the quick reply:
Here is the info for the site that reported it first.
Moodle 3.11.9 (Build: 20220822)

My feedbackreport_myfeedback | 2.16 (Build: 2022122100)2022122100

It has also happened with the same pluginversion on a Moodle 4:
4.0.6 (Build: 20230116)

**Comment by aspark21** [comment]
Should be fixed in main branch
