### ISSUE TITLE
The class report_myfeedback should go to locallib.php

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#5]
The class report_myfeedback is defined in the index.php file. Custom class definitions should go to locallib.php file, or (in recent versions) ideally into the classes directory so they can be used by the Moodle autoloading mechanism.
Also, is there any reason why the class extends the block_base class? It does not really look natural in this context.

**Comment by jgramp** [comment]
Moved the class to lib.php and removed the extension of block_base class in version 1.2
