### ISSUE TITLE
Qualification registration error

### ISSUE THREAD

**Issue by ShilVita** [jgramp/moodle-report_myfeedback#50]
Hello, please I would like guidance.

I work with Moodle version 3.11.4+ (Build: 20220111) and myfeedback version 2.16 (Build: 2022122100).

I have my own letter grading system but in the reports I load a different one, the one that comes by default in Moodle.
For example, we configure our qualification system to assign other types of letters such as: AD, A, B and C but the letters F,D,D+,C-,C+,B-B,B+,A- and A appear in the reports , this is the default Moodle system.

What should I configure to upgrade to my existing rating system?

Report Image: https://ibb.co/HhMV1nh

Thank you so much!

**Comment by aspark21** [comment]
Sounds like you need to read. up on Moodle Scales - https://docs.moodle.org/404/en/Scales

not related to this plugin so closing this issue
