### ISSUE TITLE
MySQL specific functions unix_timestamp(current_timestamp))

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#7]
The queries used MySQL specific `unix_timestamp(current_timestamp))` functions. This makes the code non-cross-db compatible. The Moodle way is to use something like `$now = time();` and then pass the value of the $now via placeholder into the SQL query - so instead of (e.g.)

```
AND (gi.hidden = 0 or gi.hidden < unix_timestamp(current_timestamp))
```

you would have something like

```
AND (gi.hidden = 0 or gi.hidden < :now)
```

**Comment by jgramp** [comment]
fixed in version 1.3
