### ISSUE TITLE
Empty string is not valid integer (unless you are on MySQL)

### ISSUE THREAD

**Issue by mudrd8mz** [jgramp/moodle-report_myfeedback#9]
MySQL is very benevolent when it comes to data types. In it, SQL like

```
'' AS assigngradeid
```

works, but on PostgreSQL this throws 

```
Debug info: ERROR: invalid input syntax for integer: ""
LINE 61: '' AS assigngradeid,
```

I would suggest to use

```
NULL AS assigngradeid
```

in this situation.

**Comment by jgramp** [comment]
fixed in v1.4 - updated the empty string to null or in the case of big integers -1, as Postgres didn't like NULL
